version: '3.8'

services:
  client:
    container_name: client
    image: client:0.0.1 
    stdin_open: true
    build:
      context: ./client
    command: npm start
    ports:
    - 3000:3000
 #  networks: onlineStore
    env_file:
      - client/.env
    #volumes:
    #  - ./src:/app/src
    depends_on:
      - server
  #  network_mode: host
  # restart: always
  server:
    container_name: server_shop
    image: server:0.0.1 
    build:
      context: ./server
    command: npm run dev
    ports:
    - 5000:5000
    #networks: onlineStore
    env_file:
      - server/.env
    environment:
      - EXTERNAL_PORT=3001
      - DB_NAME=online_store
      - DB_USER=Galaxy
      - DB_PASSWORD=admin
      - DB_HOST=postgres
    volumes:
      - .:/app
    #  - ./node_modules:/app/node_modules
    #  -  /app/server
    #volumes:
    #  - ./src:/usr/app/
    #  - ./src/node_modules:/usr/app/node_modules
    depends_on:
      - postgres
   # restart: always
  postgres:
    container_name: postgres_shop
    image: "postgres"
    ports:
      - 5432:5432
    #networks: onlineStore
    environment:
      - POSTGRES_USER=Galaxy
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=online_store
    volumes:
      - pgdata:/var/lib/postgresql/data 
    env_file:
      - server/.env
    
   
    
    #restart: always

volumes:
  pgdata: {}
    